import { MigrationInterface, QueryRunner } from 'typeorm';
import { createHash } from 'crypto';
import { ClaudeBackendProfile } from '../../entities/ClaudeBackendProfile';
import { Workspace } from '../../entities/Workspace';
import { WorkspaceClaudeBackendProfile } from '../../entities/WorkspaceClaudeBackendProfile';
import { parseCliRuntimeProfiles } from '../../common/cli-runtime-profiles';
import { runtimeToProfileEntity } from '../../common/claude-backend-registry';
import { Board } from '../../entities/Board';
import { Agent } from '../../entities/Agent';
import { Ticket } from '../../entities/Ticket';

/** Data-only migration; synchronize creates the additive schema first. */
export class BackfillGlobalClaudeBackendProfiles1760000000066 implements MigrationInterface {
  name = 'BackfillGlobalClaudeBackendProfiles1760000000066';

  async up(queryRunner: QueryRunner): Promise<void> {
    const profiles = queryRunner.manager.getRepository(ClaudeBackendProfile);
    const links = queryRunner.manager.getRepository(WorkspaceClaudeBackendProfile);
    const workspaces = queryRunner.manager.getRepository(Workspace);
    const fingerprintToId = new Map<string, string>();
    for (const row of await profiles.find()) {
      const fingerprint = createHash('sha256').update(JSON.stringify({
        protocol: row.protocol, base_url: row.base_url, model: row.model,
        credential_ref: row.credential_ref, config: JSON.parse(row.config || '{}'),
      })).digest('hex');
      fingerprintToId.set(fingerprint, row.id);
    }

    for (const workspace of await workspaces.find()) {
      if (workspace.claude_backend_profiles_migrated) continue;
      const legacy = parseCliRuntimeProfiles(workspace.cli_runtime_profiles);
      const idMap = new Map<string, string>();
      for (const runtime of legacy) {
        const candidate = runtimeToProfileEntity(runtime, runtime.id);
        const fingerprint = createHash('sha256').update(JSON.stringify({
          protocol: candidate.protocol, base_url: candidate.base_url, model: candidate.model,
          credential_ref: candidate.credential_ref, config: JSON.parse(candidate.config),
        })).digest('hex');
        let globalId = fingerprintToId.get(fingerprint);
        if (!globalId) {
          globalId = runtime.id;
          const idCollision = await profiles.findOne({ where: { id: globalId } });
          if (idCollision) globalId = `legacy-${fingerprint.slice(0, 24)}`;
          let name = runtime.id;
          const nameCollision = await profiles.findOne({ where: { name } });
          if (nameCollision) name = `${runtime.id}-${fingerprint.slice(0, 8)}`;
          await profiles.save(profiles.create({ ...candidate, id: globalId, name }));
          fingerprintToId.set(fingerprint, globalId);
        }
        idMap.set(runtime.id, globalId);
        await links.upsert(
          { workspace_id: workspace.id, profile_id: globalId },
          ['workspace_id', 'profile_id'],
        );
      }
      const legacyDefault = workspace.default_cli_runtime_profile;
      workspace.default_claude_backend_profile_id =
        legacyDefault && legacyDefault !== 'none' ? (idMap.get(legacyDefault) ?? legacyDefault) : legacyDefault;
      workspace.claude_backend_profiles_migrated = true;
      await workspaces.save(workspace);
      // A stable legacy id can name different payloads in different
      // workspaces. When that forces a deterministic global-id suffix, remap
      // every scoped selector so it still resolves to the original payload.
      for (const [legacyId, globalId] of idMap) {
        if (legacyId === globalId) continue;
        await queryRunner.manager.getRepository(Board).update(
          { workspace_id: workspace.id, cli_runtime_profile: legacyId },
          { cli_runtime_profile: globalId },
        );
        await queryRunner.manager.getRepository(Agent).update(
          { workspace_id: workspace.id, cli_runtime_profile: legacyId },
          { cli_runtime_profile: globalId },
        );
        await queryRunner.manager.getRepository(Ticket).update(
          { workspace_id: workspace.id, cli_runtime_profile: legacyId },
          { cli_runtime_profile: globalId },
        );
      }
    }
  }

  // Legacy columns are deliberately retained, so rollback only removes data
  // generated by the new registry schema (the schema itself is synchronize-owned).
  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.manager.getRepository(WorkspaceClaudeBackendProfile).clear();
    await queryRunner.manager.getRepository(ClaudeBackendProfile).clear();
    await queryRunner.manager.getRepository(Workspace).update(
      {},
      { default_claude_backend_profile_id: null, claude_backend_profiles_migrated: false },
    );
  }
}
