import assert from 'node:assert/strict';
import test from 'node:test';
import { readFile } from 'node:fs/promises';
import {
  AgentContextPreflightError,
  buildAgentContextContract,
  renderAgentContextContract,
} from '../dist/lib/agent-context-contract.js';

const ticket = {
  id: 'ticket-1', workspace_id: 'workspace-1', board_id: 'board-1',
  current_column_id: 'column-1', current_column_name: 'In Progress', current_column_kind: 'active',
  comments: [{ created_at: '2026-08-27', author: 'Agent', content: '조사 완료; 다음은 테스트' }],
};
const repository = {
  resourceId: 'repo-1', cwd: '/work/ticket-1', baseBranch: 'main', baseSha: 'base-sha',
  currentSha: 'head-sha', workingBranch: 'ticket/ticket-1-work', dirty: true,
  ahead: 2, behind: 0, resumed: true,
};

test('provider와 무관하게 동일한 의미 계약을 직렬화한다', () => {
  const common = { ticket, role: 'assignee', repository, harness: { model: 'model-a', permission_mode: 'strict' } };
  const claude = buildAgentContextContract({ ...common, sessionMode: 'persistent' });
  const codex = buildAgentContextContract({ ...common, sessionMode: 'persistent' });
  assert.deepEqual(codex, claude);
  assert.match(renderAgentContextContract(claude), /"currentSha": "head-sha"/);
  assert.match(renderAgentContextContract(claude), /조사 완료/);
});

test('필수 column 누락은 실행 전 분류된 오류가 된다', () => {
  assert.throws(
    () => buildAgentContextContract({ ticket: { id: 'ticket-1' }, role: 'assignee' }),
    (error) => error instanceof AgentContextPreflightError && error.category === 'column',
  );
});

test('credential 원문과 과거 코멘트 크기를 계약에서 제한한다', () => {
  const contract = buildAgentContextContract({
    ticket: { ...ticket, comments: [{ content: 'x'.repeat(4000) }] }, role: 'assignee', repository,
  });
  const rendered = renderAgentContextContract(contract);
  assert.equal(contract.priorProgress[0].content.length, 1200);
  assert.doesNotMatch(rendered, /token|password|credential_ref/i);
});

test('AGENTS.md는 CLAUDE.md 공통 원본에서 생성된 상태다', async () => {
  const root = new URL('../../../', import.meta.url);
  const source = await readFile(new URL('CLAUDE.md', root), 'utf8');
  const agents = await readFile(new URL('AGENTS.md', root), 'utf8');
  assert.ok(agents.endsWith(source));
  assert.match(agents, /GENERATED by scripts\/sync-agent-instructions\.mjs/);
});
